#
#  Make the Xinu version of the C run-time support library
#
 
CFLAGS  =       -fno-builtin -Wall -Wstrict-prototypes -fno-builtin -O -c -I../../h
SFLAGS  =       -I../../h
AR      =       ar
CC      =       gcc -m32 -march=i386
AS      =       as --32
LIB     =       ..
 
include ./Makefile.lib                                                          
